sudo: false

language: php

php: [7, 7.1]

before_script:
  - composer install
  - mkdir -p ./var

script:
  - composer run-script cover
  - composer run-script check-style
  - composer run-script infection

after_script:
  - composer coveralls