parameters:
    oxidmod_rest.json_api.base_url: '/'
    oxidmod_rest.serializer: oxidmod_rest.serializer.json_api
    oxidmod_rest.response_content_type: ~

services:
    oxidmod_rest.manager:
        class: League\Fractal\Manager
        calls:
            - method: setSerializer
              arguments:
                  - "@=service(parameter('oxidmod_rest.serializer'))"

    oxidmod_rest.transformer:
        class: Oxidmod\RestBundle\Transformer\Transformer
        arguments:
            - []

    oxidmod_rest.serializer.json_api:
        class: League\Fractal\Serializer\JsonApiSerializer
        arguments:
            - '%oxidmod_rest.json_api.base_url%'

    oxidmod_rest.serializer.array:
        class: League\Fractal\Serializer\ArraySerializer

    oxidmod_rest.serializer.data_array:
        class: League\Fractal\Serializer\DataArraySerializer

    oxidmod_rest.response_modifier:
        class: Oxidmod\RestBundle\Response\ResponseModifier
        arguments:
            - '@request_stack'
            - []

    oxidmod_rest.response_modifier.content_type:
        class: Oxidmod\RestBundle\Response\Modifier\ContentTypeModifier
        arguments:
            - '%oxidmod_rest.response_content_type%'
        tags:
            - { name: oxidmod_rest.response_modifier }

    oxidmod_rest.response_renderer:
        class: Oxidmod\RestBundle\Response\ResponseRenderer
        arguments:
            - '@oxidmod_rest.manager'
            - '@oxidmod_rest.transformer'
            - '@oxidmod_rest.response_modifier'
